<?php
include "../part/head_head.php";
?>
<?php
include "../part/head.php";
?>
<?php
include "../part/portfolio_head.php";
?>
&nbsp;&nbsp;&nbsp;&nbsp;<a href="portfolio_C.php" onclick="movePage(this); return false;" class="btn-next">List View<div></div></a>
<div>
    <div class="content-box flex blur-in-before-hidden">
        <div class="box-1-1 flex flex-direction flex-1-0-0 flex-jc-c">
            <div data-blur-in-duration="1.5" class="blur-in blur-in-type-1 blur-in-type-1-normal" data-trigger-inactive-delay="0" data-trigger-active-delay="2000">
                <div class="blur-item img-box">
                    <img src="https://kima-rin.github.io/img1/me/cp_content.svg" alt="">
                </div>
            </div>
            <div data-blur-in-duration="2.5" class="blur-in blur-in-type-1 blur-in-type-1-right block relative" data-trigger-inactive-delay="0" data-trigger-active-delay="3000">
                <div class="blur-item img-box flex active" data-tab-name="box-1" data-tab-head-item-name="1">
                    <img src="https://kima-rin.github.io/img1/me/cp_01.svg" alt="">
                    <div><img src="https://kima-rin.github.io/img1/me/chapter_arrow.svg" width="30" alt=""></div>
                </div>
            </div>
            <div data-blur-in-duration="2.5" class="blur-in blur-in-type-1 blur-in-type-1-right" data-trigger-inactive-delay="0" data-trigger-active-delay="3000">
                <div class="blur-item img-box flex" data-tab-name="box-1" data-tab-head-item-name="2">
                    <img src="https://kima-rin.github.io/img1/me/cp_02.svg" alt="">
                    <div><img src="https://kima-rin.github.io/img1/me/chapter_arrow.svg" width="30" alt=""></div>
                </div>
            </div>
            <div data-blur-in-duration="2.5" class="blur-in blur-in-type-1 blur-in-type-1-right" data-trigger-inactive-delay="0" data-trigger-active-delay="3000">
                <div class="blur-item img-box flex" data-tab-name="box-1" data-tab-head-item-name="3">
                    <img src="https://kima-rin.github.io/img1/me/cp_03.svg" alt="">
                    <div><img src="https://kima-rin.github.io/img1/me/chapter_arrow.svg" width="30" alt=""></div>
                </div>
            </div>
        </div>

        <div class="box-2-2 flex-1-0-0">
            <div class="list-1 flex-direction flex-jc-c flex-ai-c active" data-tab-name="box-1" data-tab-body-item-name="1">
                <div class="list-wrapper-1 flex">
                    <div class="list-box-1">
                        <div data-blur-in-duration="1.0" class="blur-in blur-in-type-1 blur-in-type-1-right number" data-trigger-inactive-delay="0" data-trigger-active-delay="4000">
                            <div class="blur-item img-box">
                                <a href="#" class="charm">NO.1</a>
                            </div>
                        </div>
                        <div data-blur-in-duration="2.0" class="blur-in blur-in-type-1 blur-in-type-1-down line" data-trigger-inactive-delay="0" data-trigger-active-delay="5000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/line.svg" alt="">
                            </div>
                        </div>
                        <div data-blur-in-duration="3.0" class="blur-in blur-in-type-1 blur-in-type-1-down pic" data-trigger-inactive-delay="0" data-trigger-active-delay="6000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/cory_01.png" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="list-box-2">
                        <div data-blur-in-duration="1.0" class="blur-in blur-in-type-1 blur-in-type-1-right number" data-trigger-inactive-delay="0" data-trigger-active-delay="4000">
                            <div class="blur-item img-box">
                                <a href="#" class="charm">NO.2</a>
                            </div>
                        </div>
                        <div data-blur-in-duration="2.0" class="blur-in blur-in-type-1 blur-in-type-1-down line" data-trigger-inactive-delay="0" data-trigger-active-delay="5000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/line.svg" alt="">
                            </div>
                        </div>
                        <div data-blur-in-duration="3.0" class="blur-in blur-in-type-1 blur-in-type-1-down pic" data-trigger-inactive-delay="0" data-trigger-active-delay="6000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/copy_02.png" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="list-box-3">
                        <div data-blur-in-duration="1.0" class="blur-in blur-in-type-1 blur-in-type-1-right number" data-trigger-inactive-delay="0" data-trigger-active-delay="4000">
                            <div class="blur-item img-box">
                                <a href="#" class="charm">NO.3</a>
                            </div>
                        </div>
                        <div data-blur-in-duration="2.0" class="blur-in blur-in-type-1 blur-in-type-1-down line" data-trigger-inactive-delay="0" data-trigger-active-delay="5000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/line.svg" alt="">
                            </div>
                        </div>
                        <div data-blur-in-duration="3.0" class="blur-in blur-in-type-1 blur-in-type-1-down pic" data-trigger-inactive-delay="0" data-trigger-active-delay="6000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/copy_03.png" alt="">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="list-wrapper-2 flex">
                    <div class="list-box-1">
                        <div data-blur-in-duration="1.0" class="blur-in blur-in-type-1 blur-in-type-1-right number" data-trigger-inactive-delay="0" data-trigger-active-delay="4000">
                            <div class="blur-item img-box">
                                <a href="#" class="charm">NO.4</a>
                            </div>
                        </div>
                        <div data-blur-in-duration="2.0" class="blur-in blur-in-type-1 blur-in-type-1-down line" data-trigger-inactive-delay="0" data-trigger-active-delay="5000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/line.svg" alt="">
                            </div>
                        </div>
                        <div data-blur-in-duration="3.0" class="blur-in blur-in-type-1 blur-in-type-1-down pic" data-trigger-inactive-delay="0" data-trigger-active-delay="6000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/copy_04.png" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="list-box-2">
                        <div data-blur-in-duration="1.0" class="blur-in blur-in-type-1 blur-in-type-1-right number" data-trigger-inactive-delay="0" data-trigger-active-delay="4000">
                            <div class="blur-item img-box">
                                <a href="#" class="charm">NO.5</a>
                            </div>
                        </div>
                        <div data-blur-in-duration="2.0" class="blur-in blur-in-type-1 blur-in-type-1-down line" data-trigger-inactive-delay="0" data-trigger-active-delay="5000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/line.svg" alt="">
                            </div>
                        </div>
                        <div data-blur-in-duration="3.0" class="blur-in blur-in-type-1 blur-in-type-1-down pic" data-trigger-inactive-delay="0" data-trigger-active-delay="6000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/blank_img.png" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="list-box-3">
                        <div data-blur-in-duration="1.0" class="blur-in blur-in-type-1 blur-in-type-1-right number" data-trigger-inactive-delay="0" data-trigger-active-delay="4000">
                            <div class="blur-item img-box">
                                <a href="#" class="charm">NO.6</a>
                            </div>
                        </div>
                        <div data-blur-in-duration="2.0" class="blur-in blur-in-type-1 blur-in-type-1-down line" data-trigger-inactive-delay="0" data-trigger-active-delay="5000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/line.svg" alt="">
                            </div>
                        </div>
                        <div data-blur-in-duration="3.0" class="blur-in blur-in-type-1 blur-in-type-1-down pic" data-trigger-inactive-delay="0" data-trigger-active-delay="6000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/blank_img.png" alt="">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="list-wrapper-3 flex">
                    <div class="list-box-1">
                        <div data-blur-in-duration="1.0" class="blur-in blur-in-type-1 blur-in-type-1-right number" data-trigger-inactive-delay="0" data-trigger-active-delay="4000">
                            <div class="blur-item img-box">
                                <a href="#" class="charm">NO.7</a>
                            </div>
                        </div>
                        <div data-blur-in-duration="2.0" class="blur-in blur-in-type-1 blur-in-type-1-down line" data-trigger-inactive-delay="0" data-trigger-active-delay="5000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/line.svg" alt="">
                            </div>
                        </div>
                        <div data-blur-in-duration="3.0" class="blur-in blur-in-type-1 blur-in-type-1-down pic" data-trigger-inactive-delay="0" data-trigger-active-delay="6000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/blank_img.png" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="list-box-2">
                        <div data-blur-in-duration="1.0" class="blur-in blur-in-type-1 blur-in-type-1-right number" data-trigger-inactive-delay="0" data-trigger-active-delay="4000">
                            <div class="blur-item img-box">
                                <a href="#" class="charm">NO.8</a>
                            </div>
                        </div>
                        <div data-blur-in-duration="2.0" class="blur-in blur-in-type-1 blur-in-type-1-down line" data-trigger-inactive-delay="0" data-trigger-active-delay="5000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/line.svg" alt="">
                            </div>
                        </div>
                        <div data-blur-in-duration="3.0" class="blur-in blur-in-type-1 blur-in-type-1-down pic" data-trigger-inactive-delay="0" data-trigger-active-delay="6000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/blank_img.png" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="list-box-3">
                        <div data-blur-in-duration="1.0" class="blur-in blur-in-type-1 blur-in-type-1-right number" data-trigger-inactive-delay="0" data-trigger-active-delay="4000">
                            <div class="blur-item img-box">
                                <a href="#" class="charm">NO.9</a>
                            </div>
                        </div>
                        <div data-blur-in-duration="2.0" class="blur-in blur-in-type-1 blur-in-type-1-down line" data-trigger-inactive-delay="0" data-trigger-active-delay="5000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/line.svg" alt="">
                            </div>
                        </div>
                        <div data-blur-in-duration="3.0" class="blur-in blur-in-type-1 blur-in-type-1-down pic" data-trigger-inactive-delay="0" data-trigger-active-delay="6000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/blank_img.png" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="list-2 flex-direction flex-jc-c flex-ai-c" data-tab-name="box-1" data-tab-body-item-name="2">
                <div class="list-wrapper-1 flex">
                    <div class="list-box-1">
                        <div data-blur-in-duration="1.0" class="blur-in blur-in-type-1 blur-in-type-1-right number" data-trigger-active-delay="4000">
                            <div class="blur-item img-box">
                                <a href="#" class="charm">NO.1</a>
                            </div>
                        </div>
                        <div data-blur-in-duration="2.0" class="blur-in blur-in-type-1 blur-in-type-1-down line" data-trigger-active-delay="5000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/line.svg" alt="">
                            </div>
                        </div>
                        <div data-blur-in-duration="3.0" class="blur-in blur-in-type-1 blur-in-type-1-down pic" data-trigger-active-delay="6000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/cre_01.png" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="list-box-2">
                        <div data-blur-in-duration="1.0" class="blur-in blur-in-type-1 blur-in-type-1-right number" data-trigger-active-delay="4000">
                            <div class="blur-item img-box">
                                <a href="#" class="charm">NO.2</a>
                            </div>
                        </div>
                        <div data-blur-in-duration="2.0" class="blur-in blur-in-type-1 blur-in-type-1-down line" data-trigger-active-delay="5000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/line.svg" alt="">
                            </div>
                        </div>
                        <div data-blur-in-duration="3.0" class="blur-in blur-in-type-1 blur-in-type-1-down pic" data-trigger-active-delay="6000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/cre_02.png" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="list-box-3">
                        <div data-blur-in-duration="1.0" class="blur-in blur-in-type-1 blur-in-type-1-right number" data-trigger-active-delay="4000">
                            <div class="blur-item img-box">
                                <a href="#" class="charm">NO.3</a>
                            </div>
                        </div>
                        <div data-blur-in-duration="2.0" class="blur-in blur-in-type-1 blur-in-type-1-down line" data-trigger-active-delay="5000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/line.svg" alt="">
                            </div>
                        </div>
                        <div data-blur-in-duration="3.0" class="blur-in blur-in-type-1 blur-in-type-1-down pic" data-trigger-active-delay="6000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/blank_img.png" alt="">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="list-wrapper-2 flex">
                    <div class="list-box-1">
                        <div data-blur-in-duration="1.0" class="blur-in blur-in-type-1 blur-in-type-1-right number" data-trigger-active-delay="4000">
                            <div class="blur-item img-box">
                                <a href="#" class="charm">NO.4</a>
                            </div>
                        </div>
                        <div data-blur-in-duration="2.0" class="blur-in blur-in-type-1 blur-in-type-1-down line" data-trigger-active-delay="5000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/line.svg" alt="">
                            </div>
                        </div>
                        <div data-blur-in-duration="3.0" class="blur-in blur-in-type-1 blur-in-type-1-down pic" data-trigger-active-delay="6000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/blank_img.png" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="list-box-2">
                        <div data-blur-in-duration="1.0" class="blur-in blur-in-type-1 blur-in-type-1-right number" data-trigger-active-delay="4000">
                            <div class="blur-item img-box">
                                <a href="#" class="charm">NO.5</a>
                            </div>
                        </div>
                        <div data-blur-in-duration="2.0" class="blur-in blur-in-type-1 blur-in-type-1-down line" data-trigger-active-delay="5000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/line.svg" alt="">
                            </div>
                        </div>
                        <div data-blur-in-duration="3.0" class="blur-in blur-in-type-1 blur-in-type-1-down pic" data-trigger-active-delay="6000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/blank_img.png" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="list-box-3">
                        <div data-blur-in-duration="1.0" class="blur-in blur-in-type-1 blur-in-type-1-right number" data-trigger-active-delay="4000">
                            <div class="blur-item img-box">
                                <a href="#" class="charm">NO.6</a>
                            </div>
                        </div>
                        <div data-blur-in-duration="2.0" class="blur-in blur-in-type-1 blur-in-type-1-down line" data-trigger-active-delay="5000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/line.svg" alt="">
                            </div>
                        </div>
                        <div data-blur-in-duration="3.0" class="blur-in blur-in-type-1 blur-in-type-1-down pic" data-trigger-active-delay="6000">
                            <div class="blur-item img-box">
                                <img src="https://kima-rin.github.io/img1/me/blank_img.png" alt="">
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
        </div>
    </div>
</div>
<script>
//enableAutoNext();
</script>
<?php
include "../part/foot.php";
?>