<?php
include "../part/head_head.php";
?>
<?php
include "../part/head.php";
?>
<?php
include "../part/portfolio_head.php";
?>
&nbsp;&nbsp;&nbsp;&nbsp;<a href="portfolio_C.php" onclick="movePage(this); return false;" class="btn-next">Next<div></div></a>
<div>
    <div class="contect-box flex">
        <div class="box-1 flex flex-1-0-0 flex-jc-c flex-ai-c">
            <div data-blur-in-duration="1.5" class="blur-in blur-in-type-1 blur-in-type-1-normal" data-trigger-active-delay="2000">
                <div class="blur-item img-box">
                    <img src="https://kima-rin.github.io/img1/me/02.png" alt="">
                </div>
            </div>
            <div data-blur-in-duration="2.5" class="blur-in blur-in-type-1 blur-in-type-1-right" data-trigger-active-delay="3000">
                <div class="blur-item img-box">
                    <img src="https://kima-rin.github.io/img1/me/nitsche.svg" alt="">
                </div>
            </div>
        </div>

        <div class="box-2 flex-1-0-0">
            <div data-blur-in-duration="2.5" class="blur-in blur-in-type-1 blur-in-type-1-left flex-1-0-0" data-trigger-active-delay="1000">
                <div class="blur-item img-box">
                    <img src="https://kima-rin.github.io/img1/me/01.png" alt="">
                </div>
            </div>
            <div data-blur-in-duration="1.5" class="blur-in blur-in-type-1 blur-in-type-1-normal absolute" data-trigger-active-delay="4000">
                <div class="blur-item img-box">
                    <img src="https://kima-rin.github.io/img1/me/rule.svg" alt="">
                </div>
            </div>
        </div>
    </div>
</div>
<script>
enableAutoNext();
</script>
<?php
include "../part/foot.php";
?>